### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by avin-kavish** [huuphongnguyen/top10trendingfonts2019-2020#1]
Are these fonts originals? If so do they have a permissive license for commercial use? I'm particular interested in Cereal and Circular.

**Comment by huuphongnguyen** [comment]
It's not originals in some specific cases, and all of these font (in this repository) you can use for testing or educating or something like that.
Airbnb cereal is the **internal font** that Airbnb have created for using in Airbnb App and their works, not public for everyone and there is no license for using in any case.
Circular is a great font. You can buy the license [here](https://lineto.com/the+fonts/font+categories/text+fonts/circular/) for commercial use.
Thank you!
